# You can use this folder to place general config files
joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

random_areas:
  - - pos_min: [-0.4, -0.4, -0.15]
      pos_max: [0.0, 0.0, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

    - pos_min: [-0.4, 0.0, -0.15]
      pos_max: [0.0, 0.4, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

  - - pos_min: [0.0, -0.4, -0.15]
      pos_max: [0.4, 0.0, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

    - pos_min: [-0.4, -0.4, -0.15]
      pos_max: [0.0, 0.0, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

  - - pos_min: [-0.4, 0.0, -0.15]
      pos_max: [0.0, 0.4, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

    - pos_min: [0.0, 0.0, -0.15]
      pos_max: [0.4, 0.4, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

  - - pos_min: [0.0, 0.0, -0.15]
      pos_max: [0.4, 0.4, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

    - pos_min: [0.0, -0.4, -0.15]
      pos_max: [0.4, 0.0, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

# robot 1
  - - pos_min: [-1.3, 0.2, -0.18]
      pos_max: [-1.1, 0.6, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]
# robot 2
  - - pos_min: [-0.6, -1.3, -0.18]
      pos_max: [-0.2, -1.1, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]
# robot 3
  - - pos_min: [0.2, 1.1, -0.18]
      pos_max: [0.6, 1.3, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]
# robot 4
  - - pos_min: [1.1, -0.6, -0.18]
      pos_max: [1.3, -0.2, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

using_areas:
  robot_1: [0, 4]
  robot_2: [1, 5]
  robot_3: [2, 6]
  robot_4: [3, 7]