# You can use this folder to place general config files
joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

random_areas:
  - - pos_min: [-0.55, -0.25, -0.2]
      pos_max: [-0.25, 0.25, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

    - pos_min: [-0.15, -0.25, -0.2]
      pos_max: [0.15, 0.25, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

    - pos_min: [0.25, -0.25, -0.2]
      pos_max: [0.55, 0.25, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

  - - pos_min: [0.35, -1.15, -0.2]
      pos_max: [0.85, -0.85, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

  - - pos_min: [0.35, 0.85, -0.2]
      pos_max: [0.85, 1.15, 0.0]
      rot_min: [-5, 175, -180]
      rot_max: [5, 185, 180]

using_areas:
  robot_1: [0, 1]
  robot_2: [0, 2]