# You can use this folder to place general config files
joint_names:
  - shoulder_pan_joint
  - shoulder_lift_joint
  - elbow_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint

random_areas:
  - - pos_min: [0.1, 0.1, -0.08]
      pos_max: [0.42, 0.34, 0.0]
      rot_min: [-15, 165, -180]
      rot_max: [15, 195, 180]

  - - pos_min: [0.8, 0.88, -0.24]
      pos_max: [1.0, 1.08, -0.23]
      rot_min: [-15, 176, -180]
      rot_max: [15, 195, 180]

  - - pos_min: [0.85, -0.68, -0.28]
      pos_max: [1.05, -0.45, -0.27]
      rot_min: [-15, 165, -180]
      rot_max: [15, 195, 180]

using_areas:
  robot_1: [0, 1]
  robot_2: [0, 2]