random_place_pose:
  pos_min: [0, 0, 0]
  pos_max: [0, 0, 0]
  quat: [1, 0, 0, 0]

place_pos_min: [-0.28, -0.45, 0.1]
place_pos_max: [-0.22, -0.35, 0.12]

vacuum_io_pins: [3]
pressure_sensor_pin: [4]
gripper_sensor_pin: [7]

infront_sucker: [0.5968870520591736, -1.3388102690326136, 0.8664364814758301, -1.097706143056051, -1.5658825079547327, -0.18301135698427373]
sucker_spot: [0.5775434374809265, -1.3343222776996058, 0.934260368347168, -1.1701415220843714, -1.565666977559225, -0.20206720033754522]

io_service: "io_and_status_controller/set_io"
io_topic: "io_and_status_controller/io_states"

init_pose: [0.7, 0.0, 0.7, 0.0, 1.0, 0.0, 0.0]
init_joints: [27.0, -110.0, 95.0, -76.0, -90.0, -108.0]

gripper_mesh_file: "/home/andy/packing_ws/install/mr_description/share/mr_description/meshes/tool/tool_no_suction.stl"
suction_mesh_file: "/home/andy/packing_ws/install/mr_description/share/mr_description/meshes/tool/tool_with_suction_323.stl"
tool_touch_links:
  - wrist_1_link
  - wrist_2_link
  - wrist_3_link

box_mesh: "/home/andy/packing_ws/install/mr_description/share/mr_description/meshes/black_box_thin.stl"
box_ring_mesh: "/home/andy/packing_ws/install/mr_description/share/mr_description/meshes/black_box_ring.stl"

