random_place_pose:
  pos_min: [0, 0, 0]
  pos_max: [0, 0, 0]
  quat: [1, 0, 0, 0]

place_pos_min: [-0.32, -0.45, -0.1]
place_pos_max: [-0.28, -0.35, -0.08]

vacuum_io_pins: [2]
pressure_sensor_pin: [3]

infront_sucker: [38.81, -84.56, 63.86, -69.23, -89.29, -5.65]
sucker_spot: [0.6200551986694336, -1.38384706178774058, 1.0053377151489258, -1.1916464010821741, -1.5656312147723597, -0.16830856004823858]

io_service: io_service
io_topic: io_topic

init_pose: [0.7, 0.0, 0.7, 0.0, 1.0, 0.0, 0.0]
init_joints: [10, -120, 120, -100, -90, -135]

gripper_mesh_file: "/home/andy/packing_ws/install/mr_description/share/mr_description/meshes/tool/tool_no_suction.stl"
suction_mesh_file: "/home/andy/packing_ws/install/mr_description/share/mr_description/meshes/tool/tool_with_suction.stl"
tool_touch_links:
  - wrist_1_link
  - wrist_2_link
  - wrist_3_link

box_mesh: "/home/andy/packing_ws/install/mr_description/share/mr_description/meshes/black_box_thin.stl"
box_ring_mesh: "/home/andy/packing_ws/install/mr_description/share/mr_description/meshes/black_box_ring.stl"

