planner_list:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - PRMkConfigDefault
    - LazyPRMkDefault
    - AdaptLazyPRMkDefault
    - BiTRRT